# Generated by Django 5.2 on 2025-11-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_updated_at_noteimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
