# Generated by Django 5.2 on 2025-11-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_note_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=10),
        ),
    ]
